secure-api:
  enabled: false
  show-log: true
  url-safe: true
  mode: common
  cipher-algorithm: rsa_ecb_sha256
  session-key-cipher-algorithm: aes_ecb_pkcs5
  key:
  iv:
  public-key:
  private-key:
  response-body-data-field:
  encrypt-url:
    include-urls: /**
    exclude-urls: /test,/test2
  decrypt-url:
    include-urls: /**
    exclude-urls:
  date-format: yyyy-MM-dd HH:mm:ss
  local-date-time-format: yyyy-MM-dd HH:mm:ss
  local-date-format: yyyy-MM-dd
  local-time-format: HH:mm:ss
